"""Render the briefing as Markdown and as a standalone HTML page."""

from __future__ import annotations

import html
from datetime import datetime, timezone

from .iso import GLOSSARY, map_controls


def _controls_line(item: dict) -> str:
    text = f"{item.get('title', '')} {item.get('summary', '')} {item.get('description', '')} {item.get('name', '')}"
    return ", ".join(f"{cid} {cname}" for cid, cname in map_controls(text))


def glossary_terms_used(stories: list[dict], cves: list[dict]) -> list[tuple[str, str]]:
    blob = " ".join(
        f"{i.get('title', '')} {i.get('summary', '')} {i.get('description', '')} {i.get('explanation', '')}"
        for i in stories + cves
    ).lower()
    used = [(term, desc) for term, desc in GLOSSARY.items() if term.lower() in blob]
    if cves:  # CVE section always benefits from the scoring primer
        for term in ("KEV", "EPSS", "CVSS"):
            if term not in [t for t, _ in used]:
                used.append((term, GLOSSARY[term]))
    return used


def to_markdown(stories: list[dict], cves: list[dict], errors: list[str]) -> str:
    today = datetime.now(timezone.utc).strftime("%A, %d %B %Y")
    lines = [f"# 🛡️ CyberBrief — {today}", "",
             "*Your daily security briefing, ranked by real-world urgency (KEV → EPSS → CVSS), explained for humans.*", ""]

    lines.append("## 🔥 Top stories\n")
    for i, s in enumerate(stories, 1):
        lines.append(f"### {i}. {s['title']}")
        lines.append(f"*{s['source']}* — [read more]({s['link']})\n")
        if s.get("explanation"):
            lines.append(f"{s['explanation']}\n")
        elif s.get("summary"):
            lines.append(f"{s['summary']}\n")
        controls = _controls_line(s)
        if controls:
            lines.append(f"> 📋 **ISO 27001:** {controls}\n")

    if cves:
        lines.append("## 🚨 CVEs that matter today\n")
        lines.append("| CVE | Why it ranks | CVSS | EPSS | Exploited? |")
        lines.append("|-----|--------------|------|------|------------|")
        for v in cves:
            why = v.get("name") or (v.get("description", "")[:80] + "…")
            kev = "⚠️ YES (KEV)" if v.get("kev") else "not yet"
            if v.get("ransomware"):
                kev += " · ransomware"
            cvss = f"{v['cvss']:.1f}" if v.get("cvss") else "–"
            lines.append(f"| **{v['cve']}** | {why} | {cvss} | {v['epss'] * 100:.0f}% | {kev} |")
        lines.append("")
        for v in cves:
            if v.get("explanation"):
                lines.append(f"**{v['cve']}** — {v['explanation']}\n")

    terms = glossary_terms_used(stories, cves)
    if terms:
        lines.append("## 📖 Jargon decoder\n")
        for term, desc in terms:
            lines.append(f"- **{term}** — {desc}")
        lines.append("")

    if errors:
        lines.append(f"<sub>Sources unavailable this run: {', '.join(errors)}</sub>\n")
    lines.append("---")
    lines.append("*Generated by [CyberBrief](https://github.com/manjou/cyberbrief) — free, open source, no AI required.*")
    return "\n".join(lines)


HTML_STYLE = """
:root { --bg:#fafaf8; --fg:#1a1d21; --muted:#6b7280; --card:#ffffff; --accent:#b91c1c;
        --border:#e5e7eb; --tag:#eef2ff; --tagfg:#3730a3; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#0f1115; --fg:#e5e7eb; --muted:#9ca3af; --card:#171a21; --accent:#f87171;
          --border:#2a2f3a; --tag:#1e2340; --tagfg:#a5b4fc; }
}
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font:16px/1.65 -apple-system, "Segoe UI", Roboto, sans-serif; }
main { max-width:760px; margin:0 auto; padding:2.5rem 1.25rem 4rem; }
h1 { font-size:1.7rem; letter-spacing:-0.02em; margin-bottom:0.25rem; }
h2 { font-size:1.15rem; margin-top:2.5rem; border-bottom:1px solid var(--border); padding-bottom:0.4rem; }
.sub { color:var(--muted); font-size:0.95rem; margin-top:0; }
article { background:var(--card); border:1px solid var(--border); border-radius:10px;
          padding:1rem 1.25rem; margin:1rem 0; }
article h3 { margin:0 0 0.2rem; font-size:1.02rem; }
article h3 a { color:var(--fg); text-decoration:none; }
article h3 a:hover { color:var(--accent); }
.src { color:var(--muted); font-size:0.82rem; }
.iso { display:inline-block; background:var(--tag); color:var(--tagfg); border-radius:6px;
       padding:0.1rem 0.55rem; font-size:0.78rem; margin-top:0.5rem; }
.tablewrap { overflow-x:auto; }
table { border-collapse:collapse; width:100%; font-size:0.88rem; }
th, td { text-align:left; padding:0.5rem 0.6rem; border-bottom:1px solid var(--border); }
.kev { color:var(--accent); font-weight:600; }
dl dt { font-weight:600; margin-top:0.7rem; }
dl dd { margin:0.1rem 0 0; color:var(--muted); }
footer { margin-top:3rem; color:var(--muted); font-size:0.85rem; }
footer a { color:inherit; }
"""


def to_html(stories: list[dict], cves: list[dict], errors: list[str]) -> str:
    today = datetime.now(timezone.utc).strftime("%A, %d %B %Y")
    e = html.escape
    parts = [f"<!doctype html><html lang='en'><head><meta charset='utf-8'>",
             "<meta name='viewport' content='width=device-width, initial-scale=1'>",
             f"<title>CyberBrief — {e(today)}</title><style>{HTML_STYLE}</style></head><body><main>",
             f"<h1>🛡️ CyberBrief</h1><p class='sub'>{e(today)} · ranked by real-world urgency "
             "(KEV → EPSS → CVSS) · explained for humans</p>"]

    parts.append("<h2>🔥 Top stories</h2>")
    for s in stories:
        parts.append("<article>")
        parts.append(f"<h3><a href='{e(s['link'])}'>{e(s['title'])}</a></h3>")
        parts.append(f"<div class='src'>{e(s['source'])}</div>")
        body = s.get("explanation") or s.get("summary") or ""
        if body:
            parts.append(f"<p>{e(body)}</p>")
        controls = _controls_line(s)
        if controls:
            parts.append(f"<span class='iso'>📋 ISO 27001: {e(controls)}</span>")
        parts.append("</article>")

    if cves:
        parts.append("<h2>🚨 CVEs that matter today</h2><div class='tablewrap'><table>")
        parts.append("<tr><th>CVE</th><th>What</th><th>CVSS</th><th>EPSS</th><th>Exploited?</th></tr>")
        for v in cves:
            why = v.get("name") or (v.get("description", "")[:90] + "…")
            kev = "<span class='kev'>YES — in CISA KEV</span>" if v.get("kev") else "not yet"
            if v.get("ransomware"):
                kev += " · ransomware use"
            cvss = f"{v['cvss']:.1f}" if v.get("cvss") else "–"
            parts.append(f"<tr><td><strong>{e(v['cve'])}</strong></td><td>{e(why)}</td>"
                         f"<td>{cvss}</td><td>{v['epss'] * 100:.0f}%</td><td>{kev}</td></tr>")
        parts.append("</table></div>")
        for v in cves:
            if v.get("explanation"):
                parts.append(f"<p><strong>{e(v['cve'])}</strong> — {e(v['explanation'])}</p>")

    terms = glossary_terms_used(stories, cves)
    if terms:
        parts.append("<h2>📖 Jargon decoder</h2><dl>")
        for term, desc in terms:
            parts.append(f"<dt>{e(term)}</dt><dd>{e(desc)}</dd>")
        parts.append("</dl>")

    if errors:
        parts.append(f"<p class='sub'>Sources unavailable this run: {e(', '.join(errors))}</p>")
    parts.append("<footer>Generated by <a href='https://github.com/manjou/cyberbrief'>CyberBrief</a> — "
                 "free · open source · no AI required · <a href='archive/'>archive</a></footer>")
    parts.append("</main></body></html>")
    return "".join(parts)
